
service: poc-1-product-sync-serveless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  indexCreation:
    handler: handler.indexProduct
    events:
      - http:
          method: post
          path: force-sync

  getProductData:
    handler: products.getProduct
    events:
      - http:
          method: post
          path: get-product

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
 individually: true

