
service: poc-1-product-sync-serveless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  indexCreation:
    handler: handler.indexProduct
    events:
      - http:
          method: post
          path: force-sync
    environment:
      INDEX_NAME: reference-article-product
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: "Ucsc@123"
      OPENSEARCH_ENDPOINT: https://search-poc-1-product-sync-eqmcszrccgxy6n4lipqipfdiiq.us-east-1.es.amazonaws.com/

  getProductData:
    handler: products.getProduct
    events:
      - http:
          method: post
          path: get-product
    environment:
      PRODUCT_URL: http://ctpm-product-api-prod.aws.wiley.com:8080/v2/products
      X_WPP_AUTH_TOKEN: X-WPP-AUTH-TOKEN
      INDEX_NAME: reference-article-product
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: "Ucsc@123"
      OPENSEARCH_ENDPOINT: https://search-poc-1-product-sync-eqmcszrccgxy6n4lipqipfdiiq.us-east-1.es.amazonaws.com/

plugins:
  - serverless-offline

package:
 individually: true

