
service: poc-1-product-sync-serveless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1

functions:
  indexCreation:
    handler: handler.indexProduct
    events:
      - http:
          method: post
          path: force-sync
    environment:
      INDEX_NAME: reference-article-product
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: "#,cN@12345"
      OPENSEARCH_ENDPOINT: https://search-poc-1-dev-product-sync-qdjw4r64lvwpg2t46655ni4ewy.us-east-1.es.amazonaws.com

plugins:
  - serverless-webpack
  - serverless-offline

#package:
#  individually: true